### ISSUE TITLE
update Action

### ISSUE THREAD

**Issue by Valery223** [video-hosting-platform/video-service#10]
# What
Вышло обновление в action, убраны некоторые аргументы(напрмер, image_name теперь не нужно), нужно чуть исправить:
```yaml
- name: Set up project
        uses: VideoHosting-Platform/actions/.github/actions/setup-and-deploy@main
        with:
          registry: 'ghcr.io'
          folder_id: '${{ secrets.FOLDER_ID }}'
          cluster_id: '${{ secrets.CLUSTER_ID }}'
          token: ${{ secrets.TOKEN }}
          yc_service_account_key: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
```
